//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Auction.Service.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AuctionEntities : DbContext
    {
        public AuctionEntities()
            : base("name=AuctionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AuctionAdvertiser> AuctionAdvertiser { get; set; }
        public virtual DbSet<AuctionCategory> AuctionCategory { get; set; }
        public virtual DbSet<AuctionGuest> AuctionGuest { get; set; }
        public virtual DbSet<AuctionObject> AuctionObject { get; set; }
        public virtual DbSet<Bidding> Bidding { get; set; }
    }
}
